version: '3.8'

services:
  qwen-tts-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qwen-tts-api
    ports:
      - "8008:8000"
    volumes:
      - .:/app
      - ./models_cache:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - CUDA_VISIBLE_DEVICES=0
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir api
    restart: unless-stopped
